[[questions]]
prompt = "What country has the highest life expectancy"
answers = ["Hong Kong"]

[[questions]]
prompt = "Where would you be if you were standing on the Spanish Steps"
answers = ["Rome"]

[[questions]]
prompt = "Which language has the more native speakers: English or Spanish"
answers = ["Spanish"]

[[questions]]
prompt = "What is the most common surname in the United States"
answers = ["Smith"]

[[questions]]
prompt = "What disease commonly spread on pirate ships"
answers = ["Scurvy"]

[[questions]]
prompt = "Who was the Ancient Greek God of the Sun"
answers = ["Apollo"]

[[questions]]
prompt = "What was the name of the crime boss who was head of the feared Chicago Outfit"
answers = ["Al Capone"]

[[questions]]
prompt = "What year was the United Nations established"
answers = ["1945"]

[[questions]]
prompt = "Who has won the most total Academy Awards"
answers = ["Walt Disney"]

[[questions]]
prompt = "What artist has the most streams on Spotify"
answers = ["Drake"]

[[questions]]
prompt = "How many minutes are in a full week"
answers = ["10,080"]

[[questions]]
prompt = "What car manufacturer had the highest revenue in 2020"
answers = ["Volkswagen"]

[[questions]]
prompt = "How many elements are in the periodic table"
answers = ["118"]

[[questions]]
prompt = "What company was originally called 'Cadabra'"
answers = ["Amazon"]

[[questions]]
prompt = "How many faces does a Dodecahedron have"
answers = ["12"]

[[questions]]
prompt = "Queen guitarist Brian May is also an expert in what scientific field"
answers = ["Astrophysics"]

[[questions]]
prompt = "Aureolin is a shade of what color"
answers = ["Yellow"]

[[questions]]
prompt = "How many ghosts chase Pac-Man at the start of each game"
answers = ["4"]

[[questions]]
prompt = "What Renaissance artist is buried in Rome's Pantheon"
answers = ["Raphael"]

[[questions]]
prompt = "What shoe brand makes the 'Mexico 66'"
answers = ["Onitsuka Tiger"]

[[questions]]
prompt = "What game studio makes the Red Dead Redemption series"
answers = ["Rockstar Games"]

[[questions]]
prompt = "Who was the last Tsar of Russia"
answers = ["Nicholas II"]

[[questions]]
prompt = "What character has both Robert Downey Jr. and Benedict Cumberbatch played"
answers = ["Sherlock Holmes"]

[[questions]]
prompt = "What country drinks the most coffee per capita"
answers = ["Finland"]

[[questions]]
prompt = "Which planet in the Milky Way is the hottest"
answers = ["Venus"]

[[questions]]
prompt = "What is the 4th letter of the Greek alphabet"
answers = ["Delta"]

[[questions]]
prompt = "What sports car company manufactures the 911"
answers = ["Porsche"]

[[questions]]
prompt = "What city is known as 'The Eternal City'"
answers = ["Rome"]

[[questions]]
prompt = "Roald Amundsen was the first man to reach the South Pole, but where was he from"
answers = ["Norway"]

[[questions]]
prompt = "What is the highest-rated film on IMDb as of January 1st, 2022"
answers = ["The Shawshank Redemption"]

[[questions]]
prompt = "Who discovered that the earth revolves around the sun"
answers = ["Nicolaus Copernicus"]

[[questions]]
prompt = "What company was initially known as 'Blue Ribbon Sports'"
answers = ["Nike"]

[[questions]]
prompt = "What art form is described as 'decorative handwriting or handwritten lettering'"
answers = ["Calligraphy"]

[[questions]]
prompt = "Which planet has the most moons"
answers = ["Saturn"]

[[questions]]
prompt = "What country has won the most World Cups"
answers = ["Brazil"]

[[questions]]
prompt = "Complete the following lyrics - 'I should have changed that stupid lock...'"
answers = ["I should have made you leave your key"]

[[questions]]
prompt = "Kratos is the main character of what video game series"
answers = ["God of War"]

[[questions]]
prompt = "In what country would you find Mount Kilimanjaro"
answers = ["Tanzania"]

[[questions]]
prompt = "What is a group of pandas known as"
answers = ["An embarrassment"]

[[questions]]
prompt = "What European country experienced the highest rate of population decline from 2015 - 2020"
answers = ["Lithuania"]

[[questions]]
prompt = "How many bones do we have in an ear"
answers = ["3"]

[[questions]]
prompt = "Who famously crossed the Alps with elephants on the way to war with the Romans"
answers = ["Hannibal"]

[[questions]]
prompt = "True or False: Halloween originated as an ancient Irish festival. "
answers = ["True"]

[[questions]]
prompt = "What Netflix show had the most streaming views in 2021"
answers = ["Squid Game"]

[[questions]]
prompt = "Which grammy-nominated New York rapper died in April of 2021"
answers = ["DMX"]

[[questions]]
prompt = "What software company is headquartered in Redmond, Washington"
answers = ["Microsoft"]

[[questions]]
prompt = "What is the largest Spanish-speaking city in the world"
answers = ["Mexico City"]

[[questions]]
prompt = "What is the world's fastest bird"
answers = ["The Peregrine Falcon"]

[[questions]]
prompt = "In what country is the Chernobyl nuclear plant located"
answers = ["Ukraine"]

[[questions]]
prompt = "The Parthenon Marbles are controversially located in what museum"
answers = ["The British Museum"]

